/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.mvc.view;
import edu.ijse.mvc.controller.ItemController;
import edu.ijse.mvc.controller.CustomerController;
import edu.ijse.mvc.controller.OrderController;
import edu.ijse.mvc.dto.ItemDto;
import edu.ijse.mvc.dto.CustomerDto;
import edu.ijse.mvc.dto.OrderDetailDto;
import edu.ijse.mvc.dto.OrderDto;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Milan
 */
public class OrderView extends javax.swing.JFrame {
    private ItemController itemController;
    private CustomerController customerController; 
    private ArrayList<OrderDetailDto>orderDeatailDtos;
    private OrderController orderController;
    /**
     * Creates new form OrderView
     */
    public OrderView() {
        itemController=new ItemController();
        customerController=new CustomerController();
        orderDeatailDtos=new ArrayList<>();
        orderController=new OrderController();
        initComponents();
        loadTable();
    }
    
   /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitle = new javax.swing.JLabel();
        lblorderid = new javax.swing.JLabel();
        lblcustid = new javax.swing.JLabel();
        lblitemid = new javax.swing.JLabel();
        txtorderid = new javax.swing.JTextField();
        txtitemid = new javax.swing.JTextField();
        txtcustid = new javax.swing.JTextField();
        btncustid = new javax.swing.JButton();
        btnitemid = new javax.swing.JButton();
        lblitemdata = new javax.swing.JLabel();
        lblcustdata = new javax.swing.JLabel();
        lblqty = new javax.swing.JLabel();
        txtqty = new javax.swing.JTextField();
        lbldiscount = new javax.swing.JLabel();
        txtdiscount = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblitem = new javax.swing.JTable();
        btnplaceorder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbltitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbltitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitle.setText("Order");

        lblorderid.setText("Order ID");

        lblcustid.setText("Cust ID");

        lblitemid.setText("Item ID");

        txtitemid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtcustid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btncustid.setText("Search");
        btncustid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncustidActionPerformed(evt);
            }
        });

        btnitemid.setText("Search");
        btnitemid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnitemidActionPerformed(evt);
            }
        });

        lblcustdata.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblqty.setText("Qty");

        lbldiscount.setText("Discount");

        btnadd.setText("Add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        tblitem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblitem);

        btnplaceorder.setText("Place Order");
        btnplaceorder.setToolTipText("");
        btnplaceorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplaceorderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblorderid)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtorderid))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblcustid)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtcustid, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btncustid)))
                        .addGap(18, 18, 18)
                        .addComponent(lblcustdata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblitemid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtitemid, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnitemid)
                        .addGap(18, 18, 18)
                        .addComponent(lblitemdata, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblqty)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(lbldiscount)
                        .addGap(18, 18, 18)
                        .addComponent(txtdiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnadd)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnplaceorder)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblorderid)
                    .addComponent(txtorderid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcustid)
                    .addComponent(txtcustid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncustid)
                    .addComponent(lblcustdata))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblitemid)
                    .addComponent(txtitemid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnitemid)
                    .addComponent(lblitemdata))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblqty)
                    .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldiscount)
                    .addComponent(txtdiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnadd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnplaceorder)
                .addGap(0, 145, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncustidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncustidActionPerformed
       searchCustomer();
    }//GEN-LAST:event_btncustidActionPerformed

    private void btnitemidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnitemidActionPerformed
       searchItem();
    }//GEN-LAST:event_btnitemidActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
       addToTable();
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnplaceorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplaceorderActionPerformed
        placeOrder();
    }//GEN-LAST:event_btnplaceorderActionPerformed
      /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new OrderView().setVisible(true);
            }
        });
    }
    private void searchItem(){
     try {
         String itemId=txtitemid.getText();
         ItemDto itemDto=itemController.searchItem(itemId);
         if(itemDto !=null){
             lblitemdata.setText(itemDto.getDescription()+" | "+itemDto.getUnitprice()+" | "+itemDto.getQoh());
         }else{
         JOptionPane.showMessageDialog(this,"item not found");
}
     } catch (Exception ex) {
         Logger.getLogger(OrderView.class.getName()).log(Level.SEVERE, null, ex);
     }
    }
    private void searchCustomer(){
        try {
            String custId=txtcustid.getText();
            CustomerDto customerDto=customerController.searchCustomer(custId);
            if(customerDto !=null){
             lblcustdata.setText(customerDto.getCustTitle()+"  "+customerDto.getCustName());
         }else{
         JOptionPane.showMessageDialog(this,"customer not found");}
        } catch (Exception ex) {
            Logger.getLogger(OrderView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void loadTable(){
        String[] columns={"Item Code","Qty","Discount"};
        DefaultTableModel dtm=new DefaultTableModel(columns,0){
        @Override
                public boolean isCellEditable(int row, int column) {
                    return false;}};
            tblitem.setModel(dtm);
    }
    private void addToTable(){
        OrderDetailDto orderDetailDto=new OrderDetailDto();
        orderDetailDto.setItemId(txtitemid.getText());
        orderDetailDto.setQty(Integer.parseInt(txtqty.getText()));
        orderDetailDto.setDiscount(Integer.parseInt(txtdiscount.getText()));
        
        orderDeatailDtos.add(orderDetailDto);
        
        Object[] rowData={orderDetailDto.getItemId(),orderDetailDto.getQty(),orderDetailDto.getDiscount()};
        
        DefaultTableModel dtm=(DefaultTableModel)tblitem.getModel();
        dtm.addRow(rowData);
        clearItemData();
    }
    private void clearItemData(){
        txtitemid.setText("");
        txtqty.setText("");
        lblitemdata.setText("");
    }
    private void placeOrder(){
        try {
            OrderDto orderDto=new OrderDto();
            orderDto.setOrderId(txtorderid.getText());
            orderDto.setCustId(txtcustid.getText());
            
            SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
            String date=sdf.format(new Date());
            orderDto.setOrderDate(date);
            
            String resp = orderController.placeOrder(orderDto,orderDeatailDtos);
            JOptionPane.showMessageDialog(this,resp);}
        catch (Exception ex) {
            Logger.getLogger(OrderView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,ex.getMessage());}
        }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btncustid;
    private javax.swing.JButton btnitemid;
    private javax.swing.JButton btnplaceorder;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcustdata;
    private javax.swing.JLabel lblcustid;
    private javax.swing.JLabel lbldiscount;
    private javax.swing.JLabel lblitemdata;
    private javax.swing.JLabel lblitemid;
    private javax.swing.JLabel lblorderid;
    private javax.swing.JLabel lblqty;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JTable tblitem;
    private javax.swing.JTextField txtcustid;
    private javax.swing.JTextField txtdiscount;
    private javax.swing.JTextField txtitemid;
    private javax.swing.JTextField txtorderid;
    private javax.swing.JTextField txtqty;
    // End of variables declaration//GEN-END:variables
}
